### PR TITLE
Add working directory support

### PR DESCRIPTION
**Pull request by damacus**
This adds the option to change directory before building the gem.
Adds support for monorepos

### CODE REVIEW

**Comment by jstastny** [comment]
Thanks a lot for this PR!
I can see you are adding some debug commits, assuming you are still fine tuning.

Let me know once you feel this is ready for merge and I will happily merge it.

**Comment by damacus** [comment]
Will do!

I just found out that it doesn't do exactly what I want it to do. Will let you know! :)

**Comment by damacus** [comment]
It didn't build the gem where I expected. But this looks like it's works for me on the workflow i'm using. 

thanks for the Action!

**Comment by jstastny** [comment]
Thanks again. Merged and released https://github.com/jstastny/publish-gem-to-github/releases/tag/v1.2

**Comment by damacus** [comment]
Ironically I've just found out that GitHub packages doesn't really support monorepos. As the gem needs to be the same name as the repo!

**Pull request merged**
